### ISSUE TITLE
Call #3 a type ascription

### ISSUE THREAD

**Issue by paulp** [ktoso/scala-types-of-types#12]
As the words "type" and "annotation" are among the most heavily overloaded in the jargon, it behooves us to avoid them if there is an alternative. I suggest this terminology:

```
5: Int               // type ascription - ascribing a type to a value
List[Int @unchecked] // what is @unchecked if not a "type annotation"
```

This usage is supported by the language specification. It is hard to misunderstand "type ascription", even if one doesn't know what it means on first encounter, but it is easy to misunderstand "type annotation" because it means more than one thing.

**Comment by ktoso** [comment]
Very good point there, lemme fix that then.
I guess I should also change "self type annotation" to be "self type ascription" to be consistent for the `x: Thing` syntaxes.

// and it seems I don't list `[X @annot]` anywhere yet, so another one to add to the list :O

**Comment by ktoso** [comment]
Thanks a load for this and the other issues, will work my way through them :)
